### PR TITLE
[WIP] Add docs prototype (Sphinx, Read the Docs)

### PR DESCRIPTION
**Pull request by EZoni**
Add prototype of documentation infrastructure based on
- Sphinx (generation)
- Read the Docs (deployment)

To-do:
- [x] Test local build
  - install dependencies from `docs/requirements.txt`
  - run `make build` in the `docs/` directory
- [ ] Test online build (on individual fork and branch)

### CODE REVIEW

**Comment by EZoni** [comment]
Additional Sphinx-friendly deployment options (e.g., GitHub Pages) can be found at https://www.sphinx-doc.org/en/master/tutorial/deploying.html.

**Comment by DavidSagan** [comment]
So this brings up the issue of what documentation environment to use (#1). I propose discussing this on the Issue forum first.

**Comment by EZoni** [comment]
@DavidSagan 

Hi, yes, a few days ago I was asked by @jlvay to open a prototype PR, precisely due to #1, in order to have a concrete example to look at and discuss during next week's meeting. The current example is based on how documentation is done in some of the BLAST codes, e.g., WarpX, which by no mean needs to be the final choice here. No intention to skip over #1.

**Comment by DavidSagan** [comment]
@EZoni Understood. Thanks for your input.

**Comment by rdemaria** [comment]
I think the choice should be the most comfortable for the maintainers/editors and will be good enough for everybody else.

I found anyway interesting sharing knowledge on documentation framework options. In this context, I would to mention a new effort to replace latex as a whole, https://typst.app/, which the maintainers/editors could also consider if they feel particularly adventurous…

**Comment by DavidSagan** [comment]
@EZoni Is this compatible with MyST?

**Pull request closed without merging**
