### PR TITLE
Instructions on how to write documentation with MyST

### PR DESCRIPTION
**Pull request by EZoni**
More (hopefully better) instructions on how to write documentation with MyST.

@jlvay @DavidSagan 
The page now looks like the following, do you think this is clear enough?

Screenshot from 2024-12-18 10-43-45

@DavidSagan 
I removed `front_matter/organization.md` from the table of contents because I could not find that file. Was this a leftover or was the file not pushed to the remote repository by mistake?

### CODE REVIEW

**Comment by EZoni** [comment]
Will add one line to remind people to commit and push their local changes too, as suggested by @jlvay.

**Comment by DavidSagan** [comment]
@EZoni Looks like `front_matter/organization.md` should be `front_matt/introduction.md`. This can get fixed now or in a later PR.

**Review by DavidSagan — APPROVED** [review]

**Comment by EZoni** [comment]
@DavidSagan 

I see that `front_matter/introduction` is already used in the beginning:
```yml
  toc:
    - file: 'front_matter/introduction.md'
    - title: 'Front Matter'
      children:
        - file: 'front_matter/governance.md'
        - file: 'front_matter/contributing.md'
        - file: 'front_matter/how_to_write_docs.md'
    - title: 'Lattice Standard'
      children:
        - file: 'standard/introduction.md'
        - file: 'standard/element_parameter.md'
```

Do you mean that you want it twice, at the top and also under "Front Matter"?

**Comment by EZoni** [comment]
I see. I think we can merge this PR (which is only related to MyST) as is and work on the organization of contents in a separate PR. 

Actually, as @cemitch99 is suggesting in #20, I think the PR template file must be in specific locations to be visible by GitHub and hence recommended as (optional or mandatory) template when opening a new PR from the web interface. 

I think the intent of that file was just to pre-populate the PR description once a new PR is open from the web interface, not necessarily to be displayed as part of the documentation. Maybe we could double check this with @cemitch99 in January.

**Comment by DavidSagan** [comment]
@EZoni OK merge first and ask questions later :).

**Pull request merged**
